### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by lkjell** [citiususc/construe#2]
Lack python3 support.

**Comment by tomas-teijeiro** [comment]
Unfortunately, we do not have the resources to maintain both Python 2 and Python 3 implementations, but in the near future we plan to migrate all the codebase to Python 3.

**Comment by lkjell** [comment]
I will port the code to python3 with 2to3 and fix some import problems. In addition pep8 formatting too.

**Comment by krivenkoz** [comment]
Hi guys! So what about Python3 support? Is it exist now?

**Comment by lkjell** [comment]
I should have a branch that support python3 at my repository.

**Comment by krivenkoz** [comment]
I didn't find. Could you provide a link to it?

**Comment by lkjell** [comment]
https://github.com/lkjell/construe/tree/python3

**Comment by krivenkoz** [comment]
Great, thanks

**Comment by krivenkoz** [comment]
When I ran run_example.sh I've got next error: 
ModuleNotFoundError: No module named 'construe.utils.signal_processing.dtw.dtw
I've read about this issue in Know issues but I can't resolve it by now. My OS is Linux Debian 9. I could not install mlpy package due to 'Failed building wheel for mlpy' error. Any suggestions?

**Comment by lkjell** [comment]
Have you read the readme file in that folder?

**Comment by lkjell** [comment]
https://github.com/lkjell/construe/blob/652396a3378277cb473e858af1b2f7cb2be9cab1/construe/utils/signal_processing/dtw/readme

**Comment by krivenkoz** [comment]
My bad, thank you. It works for me now after replacing some methods in plotter.py to modern one(nodes_iter() to nodes(), set_axis_bgcolor() to set_facecolor()). What about the Windows 10 x64? Do I have a chance to launch Construe?  At the moment I have errors with dtw,pygraphviz and some else.

**Comment by hsiaocy** [comment]
Hi @lkjell, thanks for your job on Python3 version! 
I want to help and use the [MIT-LCP's wfdb-python repository](https://github.com/MIT-LCP/wfdb-python) as a pure python environment, and decrease the dependency problems. 
While I ran the construe_ecg.py in your repository, the error pop up with a "Not Implemented Error". 
Could you please help me to fix this issue?

The error context happens from this function "process_record_rhythm()" in construe_ecg.py module and so on:
`File "/Users/AppleUser/PycharmProjects/construe-python3/construe_ecg.py", line 256, in <module>
    Rec.exclude_twaves, Rec.verbose)

  File "/Users/AppleUser/PycharmProjects/construe-python3/record_processing.py", line 498, in process_record_rhythm
    cntr.step(filt)

  File "/Users/AppleUser/PycharmProjects/construe-python3/construe/inference/searching.py", line 182, in step
    self._update_closed(newclosed)

  File "/Users/AppleUser/PycharmProjects/construe-python3/construe/inference/searching.py", line 132, in _update_closed
    self.closed.append(tmplst.pop(0))

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sortedcontainers/sortedlist.py", line 1279, in append
    raise NotImplementedError('use ``sl.add(value)`` instead')
NotImplementedError: use ``sl.add(value)`` instead`

Please ask if any question. Thanks!

**Comment by lkjell** [comment]
You could try to monkey patch th code and use the method add instead of append for self.closed. Not sure why that happen. Could be later version of sortedcontainer breaks the api.

**Comment by hsiaocy** [comment]
Sorry, I didn't notice the replacement message 'use sl.add(value) instead'. It works with following:
self.closed.append(tmplst.pop(0))
change to --> self.closed.add(tmplst.pop(0))

**Comment by karimkhanp** [comment]
@lkjell  Thanks for python3 version of construe. 

I installed all dependencies in my Mac machine python3 venv. 

Now when I try to run 

`./run_example.sh fig4`

It gives me an error with python2 code lines - 

```
Running: python -i fragment_processing.py -r examples/fig4
Traceback (most recent call last):
  File "fragment_processing.py", line 12, in <module>
    import construe.utils.plotting.plotter as plotter
  File "/Users/construe/construe/construe/utils/plotting/plotter.py", line 11, in <module>
    import construe.knowledge.observables as o
  File "/Users/construe/construe/construe/knowledge/observables/__init__.py", line 7, in <module>
    from .CardiacCycles import *
  File "/Users/construe/construe/construe/knowledge/observables/CardiacCycles.py", line 11, in <module>
    from construe.model import Observable, singleton_observable
  File "/Users/construe/construe/construe/model/__init__.py", line 5, in <module>
    from .abstraction_pattern import AbstractionPattern
  File "/Users/construe/construe/construe/model/abstraction_pattern.py", line 13, in <module>
    from .constraint_network import ConstraintNetwork, InconsistencyError, verify
  File "/Users/construe/construe/construe/model/constraint_network.py", line 429
    print 'v0:' + str(v0) + ' v1:' + str(v1) +\
              ^
SyntaxError: invalid syntax
```
I converted to python3 print syntax and run it. So it gave another error 


`
Traceback (most recent call last):
  File "fragment_processing.py", line 12, in <module>
    import construe.utils.plotting.plotter as plotter
  File "/Users/construe/construe/construe/utils/plotting/plotter.py", line 12, in <module>
    import construe.knowledge.abstraction_patterns as ap
  File "/Users/construe/construe/construe/knowledge/abstraction_patterns/__init__.py", line 6, in <module>
    from .rhythm import (RHYTHMSTART_PATTERN, SINUS_PATTERN, TACHYCARDIA_PATTERN,
  File "/Users/construe/construe/construe/knowledge/abstraction_patterns/rhythm/__init__.py", line 11, in <module>
    from .patterns import *
  File "/Users/construe/construe/construe/knowledge/abstraction_patterns/rhythm/patterns.py", line 13, in <module>
    from construe.knowledge.constants import (PW_DURATION, ST_INTERVAL,
  File "/Users/construe/construe/construe/knowledge/constants.py", line 12, in <module>
    import construe.acquisition.signal_buffer as SIG
  File "/Users/construe/construe/construe/acquisition/signal_buffer.py", line 11, in <module>
    import segmentation.wavelets.wavelet_filter as wf
ModuleNotFoundError: No module named 'segmentation'
`

**Comment by lkjell** [comment]
@karimkhanp perhaps you are not on the python3 branch.

**Comment by karimkhanp** [comment]
@lkjell Thanks for so quick reply.  You are right. I am not sure someone tried this on Mac or not, so just adding step by step progress here -

I did 

`python3 setup.py build_ext --inplace`

in `dtw` folder

Which asked me to install `Cython`. After installing Cython when I run setup file

Which ended with 
`
33 warnings generated.
clang -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.7/./cdtw.o build/temp.macosx-10.13-x86_64-3.7/./dtw.o -lm -o /Users/karim/Documents/projects/avidheart/construe/construe/utils/signal_processing/dtw/dtw.cpython-37m-darwin.so`

Believing above command completed successfully, I run test example 

`
./run_example.sh fig4
Running: python3 -i fragment_processing.py -r examples/fig4
/Users/karim/Documents/venv/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator OneClassSVM from version 0.18 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "fragment_processing.py", line 12, in <module>
    import construe.utils.plotting.plotter as plotter
  File "/Users/construe/construe/utils/plotting/plotter.py", line 15, in <module>
    from matplotlib.pyplot import figure
  File "/Users/karim/Documents/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2374, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/karim/Documents/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/karim/Documents/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/karim/Documents/venv/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.

`

**Comment by karimkhanp** [comment]
To resolve this -
```
import matplotlib
matplotlib.use('PS')
```
As mentioned on (https://github.com/scikit-optimize/scikit-optimize/issues/637)

Now 

```
./run_example.sh fig4
Running: python3 -i fragment_processing.py -r examples/fig4
/Users/karim/Documents/venv/lib/python3.7/site-packages/sklearn/base.py:251: UserWarning: Trying to unpickle estimator OneClassSVM from version 0.18 when using version 0.20.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Preloading buffer...
Starting interpretation
     0:10
     0:10
Traceback (most recent call last):
  File "/Users/construe/construe/inference/reasoning.py", line 276, in multicall_succ
    nxt = nxt or next(successors)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "fragment_processing.py", line 93, in <module>
    cntr.step(filt)
  File "/Users/construe/construe/inference/searching.py", line 171, in step
    if self.successors[n.node].hasnext():
  File "/Users/construe/construe/utils/predictable_iter.py", line 48, in hasnext
    self._thenext = next(self.iter)
  File "/Users/construe/construe/inference/reasoning.py", line 240, in firm_succ
    suc = next(generator)
RuntimeError: generator raised StopIteration
```

Referring some articles I found this is python 3.7 issue. Author's code might be reffering to older python3 version.

**Comment by lkjell** [comment]
@karimkhanp It is hard to tell. But you might try python 3.5 and use packages which was released at Dec 10, 2017. I suspect that some dependency packages changed their API. Beside the classifier for detecting P wave is quite old. Last time I talked to @tomas-teijeiro he did not have the training data.

**Comment by tomas-teijeiro** [comment]
Dear all,

We just released a new version of Construe, with all code translated to Python 3. The interpretation algorithms have also been refactored to reduce the computing requirements, so we suggest you to move to the new version. @karimkhanp our last tests were made with python 3.6 and everything worked as expected, but I will try with python 3.7 and see if there are some regression issues. Thanks @lkjell for your help!
